name: python-build-ci

on:
  push:
    branches: [ "main", "deploy" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build Day4/python/api --file Day4/python/api/Dockerfile --tag oakcrdev.azurecr.io/python-app:$(date +%s) 
